import random
oyunlar = [
    "Swords & Shields",
    "Mage's Quest",
    "Dungeons of Darkness",
    "Adventures of the Lost Kingdom",
    "Legends of Mystic Land",
    "Battle Royale",
    "Realm of Magic",
    "Mystic Maze",
    "Knights of Honor",
    "Warriors of Destiny",
    "Pubg Mobile",
    "Effotball 2024 Mobile",
    "Dünya Süper Lig",
    "Gta 5",
    "FC Mobile",
    "Vice Online",
    "Soccer Star",
    "Standoff 2",
    "Subway Surfers",
    "Clans Of Clansh",
    "City Of Crime",
    "MineCraft",
    "Meta Football",
    "Words Of Wonders",
    "Brawl Stars",
    "HayDay",
    "Cristal Strike",
    "World War 2",
    "Stumble Guys",
    "Match Fastory",
    "Satranç",
    "Okey",
    "Dama",
    "Bird Alone",
    "Clash Royale",
    "Gta 4",
    "Critical Ops",
    "Fifa",
    "Call of duty",
]

oyun = random.choice(oyunlar)
print("Oyun:",oyun)